ReadJsonOlympicGames/Controllers/CompetitionController.cs
using ReadJsonOlympicGames.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReadJsonOlympicGames.Controllers
{
    public class CompetitionController : Controller
    {
        OGData.Repository _repository = new OGData.Repository();
        // GET: Competition

        public ActionResult GetAllCompetitions()
        {
            var competitions = _repository.GetAllCompetitions();

            Competitions com = new Competitions();
            com.competitions = competitions.Select(x => new CompetitionTable
            {
                id = x.id,
                nameOfCompetition = x.nameOfCompetition,
                sportName = x.sportName,
                startDate = x.startDate,
                time = x.time,
                status = x.status,
                athletes = x.TableOfUsers.Select(y => new UserTable { id = y.id, badgeNumber = y.badgeNumber, firstName = y.firstName, lastName = y.lastName, nationality = y.nationality }).ToList()
            }).ToList();


            return View("CompetitionList", com);
        }
        public ActionResult CreateCompetition()
        {
            var listOfSports = _repository.GetAllSports();
            Sports s = new Sports();
            s.sports = listOfSports.Select(x => new OlympicSports { id = x.id, nameOfSport = x.nameOfSport }).ToList();
            return View("CreateCompetition", s);
        }

        public ActionResult ChosenSport(string sport)
        {
            var specAthletes = _repository.GetSpecificAthletes(sport);
            UsersInserted users = new UsersInserted();
            users.users = specAthletes.Select(x => new UserTable { id = x.id, firstName = x.firstName, lastName = x.lastName, badgeNumber = x.badgeNumber, nationality = x.nationality }).ToList();
            ViewBag.sport = sport;
            return View("AddCompetitionDetails", users);
        }

        [HttpPost]
        public ActionResult SaveCompetition(FormCollection collection)
        {
            if (_repository.UniqueCompetitionName((collection["nameOfCompetition"])) && collection["nameOfCompetition"] != "" && collection["description"] != "" && collection["sport"] != "" && collection["startDate"] != "" && collection["time"] != "")
            {
                _repository.SaveCompetition(collection["nameOfCompetition"], collection["description"], collection["sport"], collection["startDate"], collection["time"]);
                var competition = _repository.GetCompetition(collection["nameOfCompetition"]);

                for (int i = 5; i < collection.Count; i++)
                {
                    var badge = collection[i];
                    _repository.AssignCompetitionToAthlete(badge, competition);
                }
                var competitions = _repository.GetAllCompetitions();

                Competitions com = new Competitions();
                com.competitions = competitions.Select(x => new CompetitionTable
                {
                    id = x.id,
                    nameOfCompetition = x.nameOfCompetition,
                    sportName = x.sportName,
                    startDate = x.startDate,
                    time = x.time,
                    status = x.status,
                    athletes = x.TableOfUsers.Select(y => new UserTable { id = y.id, badgeNumber = y.badgeNumber, firstName = y.firstName, lastName = y.lastName, nationality = y.nationality }).ToList()
                }).ToList();
                return View("CompetitionList", com);
            }
            else
            {
                var specAthletes = _repository.GetSpecificAthletes(collection["sport"]);
                UsersInserted users = new UsersInserted();
                users.users = specAthletes.Select(x => new UserTable { id = x.id, firstName = x.firstName, lastName = x.lastName, badgeNumber = x.badgeNumber, nationality = x.nationality }).ToList();
                ViewBag.sport = collection["sport"];
                ViewBag.error = "Choose another competition name or fill the inputs!";
                return View("AddCompetitionDetails", users);
            }
        }

        public ActionResult DeleteCompetition(int id)
        {
            _repository.DeleteCompetition(id);
            var competitions = _repository.GetAllCompetitions();

            Competitions com = new Competitions();
            com.competitions = competitions.Select(x => new CompetitionTable
            {
                id = x.id,
                nameOfCompetition = x.nameOfCompetition,
                sportName = x.sportName,
                startDate = x.startDate,
                time = x.time,
                status = x.status,
                athletes = x.TableOfUsers.Select(y => new UserTable { id = y.id, badgeNumber = y.badgeNumber, firstName = y.firstName, lastName = y.lastName, nationality = y.nationality }).ToList()
            }).ToList();


            return View("CompetitionList", com);
        }

        public ActionResult CompetitionDetails(string comName)
        {
            var competition = _repository.GetCompetition(comName);
            var list = _repository.CompetitionMedals(comName);
            CompetitionTable com = new CompetitionTable();
            com.id = competition.id;
            com.nameOfCompetition = comName;
            com.sportName = competition.sportName;
            com.startDate = competition.startDate;
            com.time = competition.time;
            com.status = competition.status;
            var athletes = _repository.GetAthletesOfCompetition(comName);
            com.athletes = athletes.Select(x => new UserTable
            {
                id = x.id,
                firstName = x.firstName,
                lastName = x.lastName,
                badgeNumber = x.badgeNumber,
                nationality = x.nationality,
                results = x.CompetitionResults.Select(y => new CompetitionResultsModel { id = y.id, nameOfCompetition = y.nameOfCompetition, result = y.result }).ToList()
            }).ToList();

            var orderedList = from s in list
                              orderby s.longestJump descending
                              select s;

            com.athletesWithMedals = orderedList.Select(x => new UserTable
            {
                id = x.id,
                firstName = x.firstName,
                lastName = x.lastName,
                nationality = x.nationality,
                badgeNumber = x.badgeNumber,
                result = x.longestJump
            }).ToList();

            com.athletesWithMedals = com.athletesWithMedals.Take(3).ToList();
            return View("CompetitionInfo", com);
        }

        [HttpPost]
        public ActionResult StartCompetition(string nameOfCompetition)
        {
            _repository.StartCompetition(nameOfCompetition);
            var competition = _repository.GetCompetition(nameOfCompetition);

            CompetitionTable com = new CompetitionTable();
            com.id = competition.id;
            com.nameOfCompetition = nameOfCompetition;
            com.sportName = competition.sportName;
            com.startDate = competition.startDate;
            com.time = competition.time;
            com.status = competition.status;
            com.athletes = competition.TableOfUsers.Select(x => new UserTable { id = x.id, firstName = x.firstName, lastName = x.lastName, badgeNumber = x.badgeNumber, nationality = x.nationality }).ToList();
            return View("CompetitionInfo", com);
        }

        [HttpPost]
        public ActionResult EndCompetition(string nameOfCompetition)
        {
            _repository.EndCompetition(nameOfCompetition);
            var competition = _repository.GetCompetition(nameOfCompetition);

            CompetitionTable com = new CompetitionTable();
            com.id = competition.id;
            com.nameOfCompetition = nameOfCompetition;
            com.sportName = competition.sportName;
            com.startDate = competition.startDate;
            com.time = competition.time;
            com.status = competition.status;
            var athletes = _repository.GetAthletesOfCompetition(nameOfCompetition);
            com.athletes = athletes.Select(x => new UserTable
            {
                id = x.id,
                firstName = x.firstName,
                lastName = x.lastName,
                badgeNumber = x.badgeNumber,
                nationality = x.nationality,
                results = x.CompetitionResults.Select(y => new CompetitionResultsModel { id = y.id, nameOfCompetition = y.nameOfCompetition, result = y.result }).ToList()
            }).ToList();


            var list = _repository.CompetitionMedals(nameOfCompetition);
            var orderedList = from s in list
                              orderby s.longestJump descending
                              select s;

            com.athletesWithMedals = orderedList.Select(x => new UserTable
            {
                id = x.id,
                firstName = x.firstName,
                lastName = x.lastName,
                nationality = x.nationality,
                badgeNumber = x.badgeNumber,
                result = x.longestJump
            }).ToList();

            com.athletesWithMedals = com.athletesWithMedals.Take(3).ToList();
            return View("CompetitionInfo", com);
        }

        public ActionResult AthleteJump(string comName, int userId)
        {
            Random rnd = new Random();
            int length = rnd.Next(44, 120);
            _repository.AddCompetitionResultToAthlete(comName, userId, length);

            var competition = _repository.GetCompetition(comName);

            CompetitionTable com = new CompetitionTable();
            com.id = competition.id;
            com.nameOfCompetition = comName;
            com.sportName = competition.sportName;
            com.startDate = competition.startDate;

ReadJsonOlympicGames/Controllers/SportController.cs
using ReadJsonOlympicGames.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReadJsonOlympicGames.Controllers
{
    public class SportController : Controller
    {
        // GET: Sport
        OGData.Repository _repository = new OGData.Repository();
        public ActionResult GetOlympicSports()
        {
            var listOfSports = _repository.GetAllSports();
            Sports sp = new Sports();
            sp.sports = listOfSports.Select(x => new OlympicSports
            {
                id = x.id,
                nameOfSport = x.nameOfSport,
                description = x.description
            }).ToList();

            return View("Sports", sp);
        }

        public ActionResult GetAthletes()
        {
            var listOfAthletes = _repository.GetAthletes();
            UsersInserted ui = new UsersInserted();
            ui.users = listOfAthletes.Select(x => new UserTable
            {
                id = x.id,
                firstName = x.firstName,
                lastName = x.lastName,
                nationality = x.nationality,
                badgeNumber = x.badgeNumber,
                sports = x.OlympicSports.Select(y => new OlympicSports { id = y.id, nameOfSport = y.nameOfSport }).ToList()
            }).ToList();

            return View("Athletes", ui);
        }
        public ActionResult AddSport()
        {
            return View();
        }

        public ActionResult DeleteAthlete(int id)
        {
            _repository.DeleteAthlete(id);
            return RedirectToAction("GetAthletes");
        }

        [HttpPost]
        public ActionResult AddSportToDb(string nameOfSport, string description)
        {
            if (_repository.UniqueSportName(nameOfSport))
            {
                _repository.InsertSport(nameOfSport, description);
                return RedirectToAction("GetOlympicSports");
            }
            else
            {
                ViewBag.error = "Sport name already exist!";
                return View("AddSport");
            }

        }

        public ActionResult AssignSports(int id)
        {
            var user = _repository.GetSpecificUser(id);
            UserTable ut = new UserTable();
            ut.id = user.id;
            ut.firstName = user.firstName;
            ut.lastName = user.lastName;
            ut.badgeNumber = user.badgeNumber;

            var lisOfSports = _repository.GetAllSports();

            ut.sports = lisOfSports.Select(x => new OlympicSports
            {

                id = x.id,
                nameOfSport = x.nameOfSport

            }).ToList();

            return View("AssignSportsToUser", ut);
        }
        [HttpPost]
        public ActionResult AssignSportToThisUser(FormCollection collection)
        {
            var userId = _repository.FindUserByBadge(collection["badge"]);
            for (int i = 1; i < collection.Count; i++)
            {
                var sportName = collection[i];
                var sport = _repository.GetSport(sportName);
                _repository.AssignSportToUser(userId, sport);
            }
            return RedirectToAction("GetAthletes");
        }
    }
}

ReadJsonOlympicGames/Views/Home/AddFile.cshtml
@{
    ViewBag.Title = "AddFile";
}
    <div align="center">
        <h2>Add File</h2>

        @using (Html.BeginForm("UploadFile", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="form-horizontal">
                <input type="file" name="txtFile" required />
                <br />
                <input type="submit" value="Upload File" class="btn btn-default" />

            </div>
        }

    </div>

ReadJsonOlympicGames/Views/Home/AllUsers.cshtml
@model ReadJsonOlympicGames.Models.UsersInserted
@{
    ViewBag.Title = "AllUsers";
}
<div align="center">
    <h2>AllUsers</h2>
    <table style="width:100%" class="table" border="1">
        @foreach (var i in Model.users)
        {
            <tr>
                <td>@i.firstName</td>
                <td> @i.lastName</td>
                <td>@i.role</td>
                <td> @Html.ActionLink("User Info", "UserInfo", "Home", new { id = i.id }, null)</td>
                <td> @Html.ActionLink("Delete", "DeleteUser", "Home", new { id = i.id }, null)</td>
                @if (i.role == "athlete")
                {
                    <td> @Html.ActionLink("Assign sports", "AssignSports", "Sport", new { id = i.id }, null)</td>
                }

            </tr>
        }
    </table>
</div>

ReadJsonOlympicGames/Views/Home/EditProfile.cshtml
@model ReadJsonOlympicGames.Models.UserTable
@{
    ViewBag.Title = "EditProfile";
}
<div align="center">
    <h2>EditProfile</h2>
    @using (Html.BeginForm("EditMyProfileNow", "Home", new { id = Model.id }))
    {
        <input type="text" name="firstName" value="@Model.firstName" />
        <input type="text" name="lastName" value="@Model.lastName" />
        <input type="text" name="nationality" value="@Model.nationality" />
        <input type="submit" value="EDIT" />
    }

</div>

ReadJsonOlympicGames/Views/Home/Index.cshtml
@model ReadJsonOlympicGames.Models.UsersInserted
@{
    ViewBag.Title = "Home Page";
}

<div align="center">


    @if (Model.users == null)
    {
        if (User.Identity.IsAuthenticated)
        {
            OGData.Repository _repository = new OGData.Repository();
            var role = _repository.UserRole(User.Identity.Name);
            var userEmail = _repository.FindUserByEmail(User.Identity.Name);
            int id;
            if (userEmail != null)
            {
                id = userEmail.id;
            }
            else
            {
                var userBadge = _repository.FindUserByBadge(User.Identity.Name);
                id = userEmail.id;
            }
            if (role == "admin")
            {
                @Html.ActionLink("My profile", "MyProfile", "Home", new { id = id }, null)<br />
                @Html.ActionLink("Add File", "AddFile", "Home")<br />
                @Html.ActionLink("Athletes", "GetAthletes", "Sport")<br />
                @Html.ActionLink("All users", "GetAllUsers", "Home")<br />
                @Html.ActionLink("Olympic sports", "GetOlympicSports", "Sport")<br />
                @Html.ActionLink("Competitions", "GetAllCompetitions", "Competition")<br />
                @Html.ActionLink("Create Competition", "CreateCompetition", "Competition")<br />

            }
            else if (role == "athlete")
            {
                @Html.ActionLink("My profile", "MyProfile", "Home", new { id = id }, null)<br />
                @Html.ActionLink("Athletes", "GetAthletes", "Sport")<br />
                @Html.ActionLink("Competitions", "GetAllCompetitions", "Competition")<br />
            }
            else if (role == "volunteer")
            {
                @Html.ActionLink("My profile", "MyProfile", "Home", new { id = id }, null)<br />
                @Html.ActionLink("Olympic sports", "GetOlympicSports", "Sport")<br />
                @Html.ActionLink("Add my sports", "AssignSports", "Sport", new { id = id }, null)<br />
                @Html.ActionLink("Competitions", "GetAllCompetitions", "Competition")<br />
                @Html.ActionLink("Create Competition", "CreateCompetition", "Competition")<br />
            }
            else if (role == "none")
            {
                @Html.ActionLink("Login", "LoginNow", "Account")
            }
        }
    }
    else
    {
        <p>Theese athlets from file are inserted into databse.</p><br />
        <table border="1">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Surname</td>
                    <td>Badge Number</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model.users)
                {
                    <tr>
                        <td>@i.id</td>
                        <td>@i.firstName</td>
                        <td>@i.lastName</td>
                        <td>@i.badgeNumber</td>
                        <td> @Html.ActionLink("Athlete Info", "UserInfo", "Home", new { id = i.id }, null)</td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
        if (ViewBag.data != null)
        {
            <p>Theese athlets are not inserted, badge number already exist in database.</p>
            foreach (var i in ViewBag.data)
            {
                @i<br />
            }
        }
        else
        {

        }

    }

</div>

ReadJsonOlympicGames/Views/Home/MyProfile.cshtml
@model ReadJsonOlympicGames.Models.UserTable
@{
    ViewBag.Title = "UserInfo";
}
<div align="center">

    <h2>My Profile</h2>

    <table border="1">
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Surname</td>
                <td>Nationality</td>
                <td>Date Of Birth</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.id</td>
                <td>@Model.firstName</td>
                <td>@Model.lastName</td>
                <td>@Model.nationality</td>
                <td>@Model.dateOfBirth</td>
                <td>@Html.ActionLink("Edit", "EditMyProfile", "Home", new {id = Model.id }, null)</td>
            </tr>
        </tbody>
    </table>

</div>

ReadJsonOlympicGames/Views/Home/UserInfo.cshtml
@model ReadJsonOlympicGames.Models.UserTable
@{
    ViewBag.Title = "UserInfo";
}
<div align="center">

    <h2>User Info</h2>

    <table border="1" class="table">
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Surname</td>
                <td>Nationality</td>
                <td>Badge Number</td>
                <td>Date Of Birth</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.id</td>
                <td>@Model.firstName</td>
                <td>@Model.lastName</td>
                <td>@Model.nationality</td>
                <td>@Model.badgeNumber</td>
                <td>@Model.dateOfBirth</td>
            </tr>
        </tbody>
    </table>

</div>